### ISSUE TITLE
Default Profile

### ISSUE THREAD

**Issue by tonydero** [APills/WATM#1]
Thanks for this nice and simple, but super useful addon!

Is the Default profile supposed to be selected by default? I think it should be, as I feel like that's usually the "standard" for addons.

As an example, in my case, I have two profiles: one that is set to 1k and the other that is set to 10k. I want everyone but a few characters to be on my Default 1k profile, but when I log in on a new character, it is set to 10k with no profile until I manually activate the Default profile.

If that's how you intend it to function, I certainly respect that, and will deal with the minor inconvenience. I just want to make sure it's functioning the way you expect.

**Comment by APills** [comment]
I actually just caused this issue by fixing new character profiles not being created and breaking the addon, I should have an update to resolve this later today or by mid day tomorrow.

**Comment by APills** [comment]
@tonydero 
This should be resolved in the 1.0.7 release, expect it to populate on Curseforge within the next 30 minutes.
